#!/usr/bin/env python3
"""Build honest stage reports without synthesizing reviewer outcomes."""

from __future__ import annotations

import csv
import json
from collections import Counter
from pathlib import Path

from fuzzyxai.ai_pre_review.contracts import read_jsonl, sha256_file

ROOT = Path(__file__).resolve().parents[2]


def main() -> None:
    study = ROOT / "study/ai_pre_review"
    reports = ROOT / "reports/ai_pre_review"
    dissertation = ROOT / "dissertation_artifacts/ai_pre_review"
    reports.mkdir(parents=True, exist_ok=True)
    dissertation.mkdir(parents=True, exist_ok=True)
    master = read_jsonl(study / "master_explanation_log.jsonl")
    cases = {(row["case_id"], row["split"], row["modality"]) for row in master}
    actions = Counter(row["action"] for row in master)
    formative_raw = ROOT / "release_evidence/ai_pre_review/raw_ai/formative"
    confirm_raw = ROOT / "release_evidence/ai_pre_review/raw_ai/confirmatory"
    human_raw = ROOT / "release_evidence/ai_pre_review/raw_human/human_reviews.jsonl"
    formative_status = "ai_pre_reviewed" if list(formative_raw.glob("*.jsonl")) else "planned_not_run"
    confirm_status = "ai_pre_reviewed" if len(list(confirm_raw.glob("AI_RUN_*.jsonl"))) == 3 else "pending_three_ai_runs"
    human_status = "human_confirmed" if human_raw.is_file() else "external_gate"
    (reports / "formative_before_after.md").write_text(
        "# Formative AI pre-review\n\n"
        f"Status: `{formative_status}`.\n\n"
        "No reviewer scores are generated by repository code. Before/after metrics become available only after external raw AI reviews are imported.\n",
        encoding="utf-8",
    )
    (reports / "confirmatory_ai_review.md").write_text(
        "# Confirmatory AI pre-review\n\n"
        f"Status: `{confirm_status}`.\n\n"
        "Three independent AI sessions are required. This report is not human validation and contains no invented agreement values.\n",
        encoding="utf-8",
    )
    (reports / "ai_human_agreement.md").write_text(
        "# AI and independent human agreement\n\n"
        f"Status: `{human_status}`.\n\n"
        "Human confirmation has not been inferred from AI output. Agreement metrics require signed responses from at least three independent experts.\n",
        encoding="utf-8",
    )
    rows = []
    for modality in ("tabular", "image", "text", "timeseries"):
        modality_rows = [row for row in master if row["modality"] == modality]
        rows.append(
            {
                "modality": modality,
                "formative_cases": len({row["case_id"] for row in modality_rows if row["split"] == "formative"}),
                "confirmatory_cases": len({row["case_id"] for row in modality_rows if row["split"] == "confirmatory"}),
                "variants": len(modality_rows),
                "ai_status": formative_status if formative_status != "planned_not_run" else "planned_not_run",
                "human_status": human_status,
            }
        )
    with (dissertation / "table_ai_pre_review_design.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    summary = {
        "schema_version": "1.0",
        "cases": len(cases),
        "variants": len(master),
        "actions": dict(actions),
        "formative_status": formative_status,
        "confirmatory_status": confirm_status,
        "human_confirmation_status": human_status,
        "stable_release_allowed": False,
        "master_sha256": sha256_file(study / "master_explanation_log.jsonl"),
    }
    (dissertation / "ai_pre_review_stage_summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"PASS: ai_pre_review_reports cases={len(cases)} ai={formative_status} human={human_status}")


if __name__ == "__main__":
    main()
